name: coin
favicon: null
layout_spectrum: 0.9454776784405112
typography_spectrum: 0.7201062482781708
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#A690A4'
    - '#B68F9D'
    - '#C8ACAB'
    - '#FBB9BF'
    - '#E376B7'
  brandStrength: 0.5188646637834609
  lightness: 0.32705927663482726
  saturation: 0.4551269393414259
  rhythmicContrast: 0.5702437374275178
purpose: []
